//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuaHangXeMay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietNhapHang
    {
        public string Ma { get; set; }
        public string MaPhieuNhap { get; set; }
        public string MaXe { get; set; }
        public string MaLinhKien { get; set; }
        public decimal GiaNhap { get; set; }
        public int SoLuong { get; set; }
        public decimal ThanhTien { get; set; }
    
        public virtual LinhKien linh_kien { get; set; }
        public virtual PhieuNhap phieu_nhap { get; set; }
        public virtual Xe xe { get; set; }
    }
}
