//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuaHangXeMay.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CuaHangXeEntities : DbContext
    {
        public CuaHangXeEntities()
            : base("name=CuaHangXeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChiTietDonHang> DsChiTietDonHang { get; set; }
        public virtual DbSet<ChiTietNhapHang> DsChiTietNhapHang { get; set; }
        public virtual DbSet<ChiTietSuaChua> DsChiTietSuaChua { get; set; }
        public virtual DbSet<DonHang> DsDonHang { get; set; }
        public virtual DbSet<KhachHang> DsKhachHang { get; set; }
        public virtual DbSet<LinhKien> DsLinhKien { get; set; }
        public virtual DbSet<NhaCungCap> DsNhaCungCap { get; set; }
        public virtual DbSet<NhanVien> DsNhanVien { get; set; }
        public virtual DbSet<PhieuNhap> PhieuNhaps { get; set; }
        public virtual DbSet<PhieuSua> DsPhieuSua { get; set; }
        public virtual DbSet<Xe> DsXe { get; set; }
    }
}
