//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuaHangXeMay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuSua
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhieuSua()
        {
            this.chi_tiet_sua_chua = new HashSet<ChiTietSuaChua>();
        }
    
        public string Ma { get; set; }
        public string MaNhanVien { get; set; }
        public string MaKhachHang { get; set; }
        public string MaXe { get; set; }
        public System.DateTime NgayLap { get; set; }
        public Nullable<System.DateTime> NgayTra { get; set; }
        public string MoTaLoi { get; set; }
        public string TinhTrang { get; set; }
        public decimal TongTien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietSuaChua> chi_tiet_sua_chua { get; set; }
        public virtual KhachHang khach_hang { get; set; }
        public virtual NhanVien nhan_vien { get; set; }
        public virtual Xe xe { get; set; }
    }
}
