//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuaHangXeMay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuSua
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhieuSua()
        {
            this.DsChiTiet = new HashSet<ChiTietSuaChua>();
        }
    
        public string Ma { get; set; }
        private string MaNhanVien { get; set; }
        private string MaKhachHang { get; set; }
        private string MaXe { get; set; }
        public System.DateTime NgayLap { get; set; }
        public Nullable<System.DateTime> NgayTra { get; set; }
        public string MoTaLoi { get; set; }
        public string TinhTrang { get; set; }
        public decimal TongTien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietSuaChua> DsChiTiet { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual Xe Xe { get; set; }
    }
}
