//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuaHangXeMay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Xe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Xe()
        {
            this.DsChiTietDonHang = new HashSet<ChiTietDonHang>();
            this.DsChiTietNhapHang = new HashSet<ChiTietNhapHang>();
            this.DsPhieuSua = new HashSet<PhieuSua>();
        }
    
        public string Ma { get; set; }
        public string Ten { get; set; }
        public string MoTa { get; set; }
        public string HangSanXuat { get; set; }
        public string BienSoXe { get; set; }
        public decimal DonGia { get; set; }
        public int SoLuong { get; set; }
        private string MaNhaCungCap { get; set; }
        public string FileHinhAnh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHang> DsChiTietDonHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietNhapHang> DsChiTietNhapHang { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuSua> DsPhieuSua { get; set; }
    }
}
