//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuaHangXeMay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Xe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Xe()
        {
            this.chi_tiet_don_hang = new HashSet<ChiTietDonHang>();
            this.chi_tiet_nhap_hang = new HashSet<ChiTietNhapHang>();
            this.phieu_sua = new HashSet<PhieuSua>();
        }
    
        public string Ma { get; set; }
        public string Ten { get; set; }
        public string MoTa { get; set; }
        public string HangSanXuat { get; set; }
        public string BienSoXe { get; set; }
        public decimal DonGia { get; set; }
        public int SoLuong { get; set; }
        public string MaNhaCungCap { get; set; }
        public string FileHinhAnh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHang> chi_tiet_don_hang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietNhapHang> chi_tiet_nhap_hang { get; set; }
        public virtual NhaCungCap nha_cung_cap { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuSua> phieu_sua { get; set; }
    }
}
